name: client lint

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "frontend"

    strategy:
      matrix:
        node-version: [16.x, 21.x]

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: lint
        run: npm run lint

      - name: tsc
        run: tsc
